[features]
seeds = false
[programs.localnet]
my_solana_app = "J2YViXKfhCZssaWMYmzGzrVgPc7dWV63zRNh49MRdwT6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/juliencaron/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
